### PR TITLE
adds 'personal_' api to web3 lib

### PR DESCRIPTION
**Pull request by ProofOfKeags**

### CODE REVIEW

**Comment by martyall** [comment]
Nice, is this one done? 

I've also made a WIP label if you ever want to use it, reason being that I'm not sure if the travis job runs on commits which are not made on a PR branch. You can include this label to use travis but no one will pay much attention to that PR until it's removed / you poke someone.

**Comment by ProofOfKeags** [comment]
I wanna get it running properly in our dev environment first, and add a few more inline pragmas. So I'll grab that WIP for now.

**Comment by ProofOfKeags** [comment]
Except I don't think I can add the WIP label myself.

**Comment by martyall** [comment]
I just labeled this one

**Comment by ProofOfKeags** [comment]
I think I'd like to mark this as complete

**Comment by martyall** [comment]
looks good, is there anything that should be tested here? If you need us to add a locked account to cliquebait (the docker node that runs in ci), we can do that.

**Pull request merged**
