### PR TITLE
added checksum features and tests

### PR DESCRIPTION
**Pull request by ProofOfKeags**
#11

### CODE REVIEW

**Comment by ProofOfKeags** [comment]
Not sure how to check the TravisCI build output

**Comment by martyall** [comment]
So that travis build matrix was left over from airalab, we just commented out the cabal builds and left only stack. Can you merge in this change and repush, will be easier to talk about travis in the future.

For now, you can click the little red X on this failure, navigate to the build with `STACK = YES`, and go to the bottom, it says something about cannot find AddressSpec in unit.

**Comment by ProofOfKeags** [comment]
I don't have the ability to merge. But I repushed with the Test in the correct directory.

**Comment by martyall** [comment]
🏄

**Comment by martyall** [comment]
Actually just one small thing first, can we put in a test for asserting that something doesn't checksum that shouldn't? Just for completeness.

**Comment by ProofOfKeags** [comment]
Done

**Comment by kejace** [comment]
Thanks!

**Pull request merged**
